[package]
name = "windows_sdk"
version = "0.0.0"
edition = "2021"
rust-version = "1.56"
publish = false
license = "MIT"

[lib]
name = "windows_sdk"
path = "lib.rs"

[[bin]]
name = "windows_sdk"
path = "main.rs"

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["color"] }
duct = "0.13"
regex = "1.5"
walkdir = "2"
